#!/usr/bin/env node
/**
 * import_to_d1.mjs
 * ─────────────────────────────────────────────────────────────────
 * Reads scripts/import.csv and generates SQL INSERT statements for D1.
 * Can also execute them directly via wrangler d1 execute.
 *
 * import.csv columns: token_hash,household_label,phone_e164,guests
 *   guests: pipe-delimited list of guest names, e.g. "Alice Smith|Bob Smith"
 *
 * Usage:
 *   # Print SQL to stdout
 *   node scripts/import_to_d1.mjs
 *
 *   # Write SQL to file
 *   node scripts/import_to_d1.mjs --output=scripts/seed.sql
 *
 *   # Execute directly against local D1 (from worker/ directory)
 *   node ../scripts/import_to_d1.mjs --output=../scripts/seed.sql
 *   cd worker && wrangler d1 execute wedding-rsvp --local --file=../scripts/seed.sql
 *
 *   # Execute against remote D1
 *   cd worker && wrangler d1 execute wedding-rsvp --file=../scripts/seed.sql
 */

import { createReadStream, existsSync, writeFileSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { argv } from 'node:process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── Args ──────────────────────────────────────────────────────────────
const args = {};
argv.slice(2).forEach(a => {
  const [k, v] = a.replace(/^--/, '').split('=');
  args[k] = v ?? true;
});

const importPath = path.join(__dirname, 'import.csv');
if (!existsSync(importPath)) {
  console.error(`import.csv not found at ${importPath}.\nRun generate_tokens.mjs first.`);
  process.exit(1);
}

// ── CSV parser ────────────────────────────────────────────────────────
function parseCsvLine(line) {
  const fields = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"' && line[i + 1] === '"') { field += '"'; i++; }
      else if (ch === '"') { inQuotes = false; }
      else { field += ch; }
    } else {
      if (ch === '"') { inQuotes = true; }
      else if (ch === ',') { fields.push(field.trim()); field = ''; }
      else { field += ch; }
    }
  }
  fields.push(field.trim());
  return fields;
}

/** Escape a string for safe SQL literal (single-quote doubling). */
function sqlStr(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

// ── Read import.csv ───────────────────────────────────────────────────
async function readImportCsv() {
  const rows = [];
  const rl = createInterface({ input: createReadStream(importPath), crlfDelay: Infinity });
  let isFirst = true;
  for await (const line of rl) {
    if (!line.trim()) continue;
    if (isFirst) { isFirst = false; continue; }
    const [token_hash, household_label, phone_e164, source_list, guests_raw] = parseCsvLine(line);
    if (!token_hash || !household_label || !phone_e164) {
      console.warn(`  ⚠️  Skipping malformed row: ${line}`);
      continue;
    }
    // guests_raw format: "Name:events1,events2|Name2:events3"
    const guests = (guests_raw ?? '').split('|').map(s => s.trim()).filter(Boolean).map(entry => {
      const colonIdx = entry.lastIndexOf(':');
      if (colonIdx === -1) return { name: entry, events: 'mehndi,shaadi,walima' };
      return { name: entry.slice(0, colonIdx).trim(), events: entry.slice(colonIdx + 1).trim() || 'mehndi,shaadi,walima' };
    });
    rows.push({ token_hash, household_label, phone_e164, source_list: source_list ?? '', guests });
  }
  return rows;
}

// ── SQL generator ─────────────────────────────────────────────────────
function generateSql(rows) {
  const lines = [
    '-- Wedding RSVP · D1 seed data',
    '-- Generated by import_to_d1.mjs',
    `-- ${new Date().toISOString()}`,
    '',
    'BEGIN TRANSACTION;',
    '',
  ];

  for (const row of rows) {
    // Insert invite (by token_hash — idempotent via INSERT OR IGNORE)
    lines.push(
      `INSERT OR IGNORE INTO invites (token_hash, household_label, phone_e164, source_list)` +
      ` VALUES (${sqlStr(row.token_hash)}, ${sqlStr(row.household_label)}, ${sqlStr(row.phone_e164)}, ${sqlStr(row.source_list)});`
    );

    // Insert guests — use a subquery to get invite_id
    for (const guest of row.guests) {
      lines.push(
        `INSERT OR IGNORE INTO guests (invite_id, full_name, events)` +
        ` VALUES (` +
        `(SELECT id FROM invites WHERE token_hash = ${sqlStr(row.token_hash)}), ` +
        `${sqlStr(guest.name)}, ` +
        `${sqlStr(guest.events)}` +
        `);`
      );
    }

    lines.push('');
  }

  lines.push('COMMIT;', '');
  return lines.join('\n');
}

// ── Main ─────────────────────────────────────────────────────────────
async function main() {
  const rows = await readImportCsv();
  if (rows.length === 0) {
    console.error('No rows found in import.csv.');
    process.exit(1);
  }

  const sql = generateSql(rows);

  if (args.output) {
    const outPath = path.resolve(process.cwd(), args.output);
    writeFileSync(outPath, sql, 'utf8');
    console.log(`\n💾  SQL written to: ${outPath}`);
    console.log('\nTo apply locally:');
    console.log('  cd worker');
    console.log(`  wrangler d1 execute wedding-rsvp --local --file=../${args.output}`);
    console.log('\nTo apply to remote D1:');
    console.log(`  wrangler d1 execute wedding-rsvp --file=../${args.output}\n`);
  } else {
    console.log(sql);
  }
}

main().catch(err => { console.error(err); process.exit(1); });
